import type {
  PurchaseOrder,
  DeliveryOrder,
  LogisticsTask,
  DashboardStats,
  SlaAlert,
} from './logistics';

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-1',
    po_number: 'PO-2026-000001',
    source_pr_codes: [],
    line_items: [
      {
        id: 'po-item-1',
        source_pr_code: '',
        source_pr_line_id: '',
        item_code: 'ITM-001',
        item_name: 'Silicon Wafer Core 8-inch',
        quantity: 5000,
        unit: 'PCS',
        warehouse_deadline_date: '2026-05-30',
        warehouse_code: 'WH001',
      },
    ],
    supplier_code: 'SUP-SUMSUNG',
    supplier_name: 'SumSung Electronics Global',
    status: 'SAP_SYNCED',
    order_date: '2026-05-15',
    currency: 'USD',
    total_amount: 77500,
    sap_sync_status: 'SYNCED',
    linked_do_numbers: ['DO-2026-000001'],
    warehouse_code: 'WH001',
    flow_tags: ['LINEAR'],
  },
  {
    id: 'po-2',
    po_number: 'PO-2026-000002',
    source_pr_codes: [],
    line_items: [
      {
        id: 'po-item-2',
        source_pr_code: '',
        source_pr_line_id: '',
        item_code: 'ITM-002',
        item_name: 'Lithium Battery Pack Cell',
        quantity: 12000,
        unit: 'PCS',
        warehouse_deadline_date: '2026-06-15',
        warehouse_code: 'WH002',
      },
    ],
    supplier_code: 'VB245',
    supplier_name: 'Đối tác VB245',
    status: 'SAP_PENDING',
    order_date: '2026-05-20',
    currency: 'USD',
    total_amount: 98400,
    sap_sync_status: 'SYNCED',
    linked_do_numbers: [],
    warehouse_code: 'WH002',
    flow_tags: ['BULK_PURCHASE'],
  },
];

export const mockDeliveryOrders: DeliveryOrder[] = [
  {
    id: 'do-1',
    order_info: {
      request_code: 'REQ-001',
      order_number: 'DO-2026-000001',
      tracking_number: 'TRK99887766',
      purchase_contract_number: 'HD-SX-2026-000001',
      status: 'IN_TRANSIT',
      notes: 'Urgent air shipment of wafers',
      xnk_notes: '',
    },
    product_details: {
      item_name_requested: 'Silicon Wafer Core 8-inch',
      unit: 'PCS',
      quantity: 5000,
      lot_number: null,
      lot_unit_quantity: null,
      lot_unit_type: null,
      packaging_type: null,
    },
    source_lines: [],
    sap_integration: {
      supplier_code: 'SUP-SUMSUNG',
      supplier_name: 'SumSung Electronics Global',
      actual_item_code: 'ITM-001',
      raw_date: null,
      po_number: 'PO-2026-000001',
      sync_status: 'SYNCED',
    },
    logistics_shipping: {
      incoterms: 'CIP',
      shipping_method: 'AIR',
      shipping_line: 'Korean Air Cargo',
      vessel_code: null,
      port_of_departure: 'Incheon (ICN)',
      port_of_destination: 'Noi Bai (HAN)',
      documents_list: ['Invoice', 'Packing List', 'B/L'],
      missing_documents: [],
      cut_off_date: null,
      etd_planned: '2026-05-22',
      eta_planned: '2026-05-23',
    },
    warehouse_tracking: {
      warehouse_code: 'WH001',
      production_ready_date: null,
      warehouse_deadline: '2026-05-30',
      planned_entry_date: '2026-05-24',
      actual_entry_date: null,
      delay_days: 0,
    },
    finance_tax: {
      import_tax_rate: 5,
      tax_amount: 3875,
      currency: 'USD',
      tax_payment_deadline: null,
      insurance: null,
    },
    task_summary: {
      total_tasks: 2,
      completed_tasks: 0,
      blocked_tasks: 0,
      required_tasks_remaining: 1,
    },
    flow_tags: ['LINEAR'],
  },
];

export const mockTasks: LogisticsTask[] = [
  {
    task_id: 'task-1',
    do_number: 'DO-2026-000001',
    hbl_number: null,
    request_code: 'REQ-001',
    po_number: 'PO-2026-000001',
    production_contract_number: 'HD-SX-2026-000001',
    task_name: 'Check customs document set',
    role: 'Customs Officer',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    progress: 50,
    due_date: '2026-05-24',
    is_required_for_do_closure: true,
    notes: 'Verify invoice and packing list values match exactly.',
    blocked_reason: null,
    completed_at: null,
    created_at: '2026-05-16',
    assigned_at: '2026-05-16',
    assignee: {
      user_id: 'usr-customs-001',
      name: 'Le Minh Chau',
      department: 'Import Customs',
    },
  },
  {
    task_id: 'task-2',
    do_number: 'DO-2026-000001',
    hbl_number: null,
    request_code: 'REQ-002',
    po_number: 'PO-2026-000001',
    production_contract_number: 'HD-SX-2026-000001',
    task_name: 'Update carrier tracking and ETA',
    role: 'Port Officer',
    status: 'TODO',
    priority: 'MEDIUM',
    progress: 0,
    due_date: '2026-05-22',
    is_required_for_do_closure: false,
    notes: 'Confirm flight KE345 has departed.',
    blocked_reason: null,
    completed_at: null,
    created_at: '2026-05-16',
    assigned_at: '2026-05-16',
    assignee: {
      user_id: 'usr-port-001',
      name: 'Pham Quoc Huy',
      department: 'Port Operations',
    },
  },
];

export const mockDashboardStats: DashboardStats = {
  totals: {
    purchaseRequests: 0,
    purchaseOrders: mockPurchaseOrders.length,
    deliveryOrders: mockDeliveryOrders.length,
    tasks: mockTasks.length,
    blockedTasks: 0,
  },
  businessFlowCounts: [
    { tag: 'LINEAR', count: 2 },
    { tag: 'BULK_PURCHASE', count: 1 },
  ],
  deliveryOrderStatus: [
    { status: 'IN_TRANSIT', count: 1 },
  ],
  taskStatus: [
    { status: 'IN_PROGRESS', count: 1 },
    { status: 'TODO', count: 1 },
  ],
  taskRoleProgress: [
    { role: 'Customs Officer', total: 1, completed: 0, completionRate: 0 },
    { role: 'Port Officer', total: 1, completed: 0, completionRate: 0 },
  ],
  monthlyThroughput: [
    { month: '2026-05', deliveryOrders: 1, completedTasks: 0 },
  ],
};

export const mockSlaAlerts: SlaAlert[] = [
  {
    entityId: 'do-1',
    entityType: 'document_review',
    message: 'Customs document set check is due soon (SLA Warning)',
    ownerRole: 'Customs Officer',
    slaDueAt: '2026-05-24T12:00:00Z',
    slaStage: 'Customs Clearance',
  },
];

export const mockDomesticTransportOrders = [
  {
    id: 'dto-1',
    requestCode: 'REQ-DTO-001',
    doNumber: 'DO-2026-000001',
    carrierCode: 'CAR-HUU-NGHI',
    carrierName: 'Logistics Hữu Nghị',
    status: 'PENDING',
    pickupAddress: 'Noi Bai (HAN) Cargo Terminal',
    deliveryAddress: 'Industrial Zone A, Hanoi',
    plannedPickupAt: '2026-05-24T08:00:00Z',
    plannedDeliveryAt: '2026-05-24T14:00:00Z',
    weightKg: 1500,
    volumeCbm: 4.5,
    quotes: [
      {
        id: 'quote-1',
        carrierCode: 'CAR-HUU-NGHI',
        carrierName: 'Logistics Hữu Nghị',
        amount: 350,
        currency: 'USD',
        isMinPrice: true,
        isSlaPassed: true,
      },
    ],
  },
];

export const mockIssues = [
  {
    id: 'issue-1',
    entityId: 'do-1',
    entityType: 'DELIVERY_ORDER',
    title: 'Customs Declaration Delay',
    description: 'Customs rejected the initial declaration due to HS code format mismatch.',
    reportedBy: 'Le Minh Chau',
    severity: 'HIGH',
    status: 'OPEN',
    createdAt: '2026-05-23T09:30:00Z',
    resolvedAt: null,
  },
];
