export const queryKeys = {
  dashboardStats: ['dashboard-stats'] as const,
  deliveryOrderAttachments: (orderNumber: string) => ['delivery-order-attachments', orderNumber] as const,
  deliveryOrders: ['delivery-orders'] as const,
  globalPoStageTasks: ['global-po-stage-tasks'] as const,
  globalSearch: ['global-search'] as const,
  globalSearchResults: (query: string) => ['global-search', query] as const,
  currencies: (params: Record<string, unknown>) => ['currencies', params] as const,
  currencyDetail: (id: string) => ['currencies', 'detail', id] as const,
  currencyLists: ['currencies'] as const,
  incotermDetail: (id: string) => ['incoterms', 'detail', id] as const,
  incotermLists: ['incoterms'] as const,
  incoterms: (params: Record<string, unknown>) => ['incoterms', params] as const,
  itemDetail: (id: string) => ['items', 'detail', id] as const,
  itemGroupDetail: (id: string) => ['item-groups', 'detail', id] as const,
  itemGroupItems: (id: string, params: Record<string, unknown>) =>
    ['item-groups', id, 'items', params] as const,
  itemGroupLists: ['item-groups'] as const,
  itemGroups: (params: Record<string, unknown>) => ['item-groups', params] as const,
  itemLists: ['items'] as const,
  items: (params: Record<string, unknown>) => ['items', params] as const,
  itemTaxProfiles: (itemId: string) => ['items', itemId, 'tax-profiles'] as const,
  masterData: ['master-data'] as const,
  masterDataOptionLists: ['master-data-options'] as const,
  masterDataOptions: (params: Record<string, unknown>) => ['master-data-options', params] as const,
  purchaseOrderTasks: (poNumber: string) => ['purchase-order-tasks', poNumber] as const,
  purchaseOrders: ['purchase-orders'] as const,
  quotations: ['quotations'] as const,
  shipmentMilestones: (shipmentId: string) => ['shipment-milestones', shipmentId] as const,
  shipments: ['shipments'] as const,
  supplierDetail: (id: string) => ['suppliers', 'detail', id] as const,
  supplierLists: ['suppliers'] as const,
  suppliers: (params: Record<string, unknown>) => ['suppliers', params] as const,
  taskTemplates: ['task-templates'] as const,
  tasks: ['tasks'] as const,
  transportModeDetail: (id: string) => ['transport-modes', 'detail', id] as const,
  transportModeLists: ['transport-modes'] as const,
  transportModes: (params: Record<string, unknown>) => ['transport-modes', params] as const,
  users: ['users'] as const,
};
