export const queryKeys = {
  dashboardStats: ['dashboard-stats'] as const,
  deliveryOrderAttachments: (orderNumber: string) => ['delivery-order-attachments', orderNumber] as const,
  deliveryOrderDocuments: (id: string) => ['delivery-orders', id, 'documents'] as const,
  deliveryOrderDetail: (id: string) => ['delivery-orders', 'detail', id] as const,
  deliveryOrderLines: (id: string) => ['delivery-orders', id, 'lines'] as const,
  deliveryOrderLists: ['delivery-orders', 'list'] as const,
  deliveryOrderLots: (id: string) => ['delivery-orders', id, 'lots'] as const,
  deliveryOrders: ['delivery-orders'] as const,
  deliveryOrdersList: (params: Record<string, unknown>) => ['delivery-orders', 'list', params] as const,
  domesticTransportOrderDetail: (id: string) => ['domestic-transport-orders', 'detail', id] as const,
  domesticTransportOrderLists: ['domestic-transport-orders', 'list'] as const,
  domesticTransportOrders: ['domestic-transport-orders'] as const,
  domesticTransportOrdersList: (params: Record<string, unknown>) =>
    ['domestic-transport-orders', 'list', params] as const,
  carrierLists: ['carriers'] as const,
  carriers: (params: Record<string, unknown>) => ['carriers', params] as const,
  carrierDetail: (id: string) => ['carriers', 'detail', id] as const,
  chargeCodeDetail: (id: string) => ['charge-codes', 'detail', id] as const,
  chargeCodeLists: ['charge-codes'] as const,
  chargeCodes: (params: Record<string, unknown>) => ['charge-codes', params] as const,
  forwarderLists: ['forwarders'] as const,
  forwarders: (params: Record<string, unknown>) => ['forwarders', params] as const,
  forwarderDetail: (id: string) => ['forwarders', 'detail', id] as const,
  globalPoStageTasks: ['global-po-stage-tasks'] as const,
  globalSearch: ['global-search'] as const,
  globalSearchResults: (query: string) => ['global-search', query] as const,
  currencies: (params: Record<string, unknown>) => ['currencies', params] as const,
  currencyDetail: (id: string) => ['currencies', 'detail', id] as const,
  currencyLists: ['currencies'] as const,
  customsDeclarationDetail: (id: string) => ['customs-declarations', 'detail', id] as const,
  customsDeclarationLines: (id: string) => ['customs-declarations', id, 'lines'] as const,
  customsDeclarationLists: ['customs-declarations', 'list'] as const,
  customsDeclarationsByShipment: (shipmentId: string) =>
    ['shipments', shipmentId, 'customs-declarations'] as const,
  incotermDetail: (id: string) => ['incoterms', 'detail', id] as const,
  incotermLists: ['incoterms'] as const,
  incoterms: (params: Record<string, unknown>) => ['incoterms', params] as const,
  itemDetail: (id: string) => ['items', 'detail', id] as const,
  itemGroupDetail: (id: string) => ['item-groups', 'detail', id] as const,
  itemGroupItems: (id: string, params: Record<string, unknown>) =>
    ['item-groups', id, 'items', params] as const,
  itemGroupLists: ['item-groups'] as const,
  itemGroups: (params: Record<string, unknown>) => ['item-groups', params] as const,
  itemLists: ['items'] as const,
  items: (params: Record<string, unknown>) => ['items', params] as const,
  itemTaxProfiles: (itemId: string) => ['items', itemId, 'tax-profiles'] as const,
  masterData: ['master-data'] as const,
  masterDataOptionLists: ['master-data-options'] as const,
  masterDataOptions: (params: Record<string, unknown>) => ['master-data-options', params] as const,
  purchaseOrderConfirmations: (id: string) => ['purchase-orders', id, 'confirmations'] as const,
  purchaseOrderDetail: (id: string) => ['purchase-orders', 'detail', id] as const,
  purchaseOrderDeliveryOrders: (id: string) => ['purchase-orders', id, 'delivery-orders'] as const,
  purchaseOrderLines: (id: string) => ['purchase-orders', id, 'lines'] as const,
  purchaseOrderLotPlanning: (id: string) => ['purchase-orders', id, 'lot-planning'] as const,
  purchaseOrderLists: ['purchase-orders', 'list'] as const,
  purchaseOrdersList: (params: Record<string, unknown>) => ['purchase-orders', 'list', params] as const,
  purchaseOrderTasks: (poNumber: string) => ['purchase-order-tasks', poNumber] as const,
  purchaseOrders: ['purchase-orders'] as const,
  quotationChargeLines: (id: string) => ['quotations', id, 'charge-lines'] as const,
  quotationDetail: (id: string) => ['quotations', 'detail', id] as const,
  quotationEvents: (id: string) => ['quotations', id, 'events'] as const,
  quotationLists: ['quotations', 'list'] as const,
  quotationsList: (params: Record<string, unknown>) => ['quotations', 'list', params] as const,
  quotationVersions: (id: string) => ['quotations', id, 'versions'] as const,
  quotations: ['quotations'] as const,
  shipmentCarrierDeliveryOrders: (shipmentId: string) =>
    ['shipments', shipmentId, 'carrier-delivery-orders'] as const,
  shipmentDetail: (id: string) => ['shipments', 'detail', id] as const,
  shipmentDtos: (shipmentId: string) => ['shipments', shipmentId, 'domestic-transport-orders'] as const,
  shipmentContainers: (id: string) => ['shipments', id, 'containers'] as const,
  shipmentDocuments: (id: string) => ['shipments', id, 'documents'] as const,
  shipmentLines: (id: string) => ['shipments', id, 'lines'] as const,
  shipmentLists: ['shipments', 'list'] as const,
  shipmentMilestones: (id: string) => ['shipments', id, 'milestones'] as const,
  shipmentsList: (params: Record<string, unknown>) => ['shipments', 'list', params] as const,
  shipments: ['shipments'] as const,
  supplierDetail: (id: string) => ['suppliers', 'detail', id] as const,
  supplierLists: ['suppliers'] as const,
  suppliers: (params: Record<string, unknown>) => ['suppliers', params] as const,
  taskTemplates: ['task-templates'] as const,
  taskTemplateLists: ['task-templates'] as const,
  taskTemplateDetail: (id: string) => ['task-templates', 'detail', id] as const,
  taskTemplatesList: (params: Record<string, unknown>) => ['task-templates', params] as const,
  tasks: ['tasks'] as const,
  transportModeDetail: (id: string) => ['transport-modes', 'detail', id] as const,
  transportModeLists: ['transport-modes'] as const,
  transportModes: (params: Record<string, unknown>) => ['transport-modes', params] as const,
  uomDetail: (id: string) => ['uoms', 'detail', id] as const,
  uomLists: ['uoms'] as const,
  uoms: (params: Record<string, unknown>) => ['uoms', params] as const,
  users: ['users'] as const,
};
