export const GD1_PREFIXES = {
  PURCHASE_REQUEST: 'PR',
  PURCHASE_ORDER: 'PO',
  SHIPMENT: 'SHP',
  DOMESTIC_TRANSPORT_ORDER: 'DTO',
  ISSUE_LOG: 'ISS',
};

export const PR_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export const PO_STATUS = {
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  CONFIRMED: 'CONFIRMED',
  IN_PRODUCTION: 'IN_PRODUCTION',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
} as const;

export const SHIPMENT_STATUS = {
  DRAFT: 'DRAFT',
  BOOKED: 'BOOKED',
  IN_TRANSIT: 'IN_TRANSIT',
  ARRIVED: 'ARRIVED',
  CUSTOMS_CLEARED: 'CUSTOMS_CLEARED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
} as const;

export const DTO_STATUS = {
  DRAFT: 'DRAFT',
  QUOTING: 'QUOTING',
  AWARDED: 'AWARDED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
} as const;

export const TASK_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  BLOCKED: 'BLOCKED',
  CANCELLED: 'CANCELLED',
} as const;

export const PRIORITY_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;
